# This file has been auto generated by the fp2p tool.
# Do not modify it by hand!
# Files used for generation:
#   Tree file: tree.yaml
#   Assignment file: assignment.yaml
# More information on the website https://github.com/m-kru/fp2p.

set_property PACKAGE_PIN D1 [get_ports {prefix_A_suffix}]
set_property IOSTANDARD LVDS_33 [get_ports {prefix_A_suffix}]
set_property DIFF_TERM TRUE [get_ports {prefix_A_suffix}]

set_property PACKAGE_PIN D2 [get_ports {B_suffix}]
set_property IOSTANDARD LVDS_33 [get_ports {B_suffix}]
set_property DIFF_TERM FALSE [get_ports {B_suffix}]

set_property PACKAGE_PIN D3 [get_ports {prefix_C}]
set_property IOSTANDARD LVDS_25 [get_ports {prefix_C}]
set_property DIFF_TERM TRUE [get_ports {prefix_C}]
