# This file has been auto generated by the fp2p tool.
# Do not modify it by hand!
# Files used for generation:
#   Tree file: tree.yaml
#   Assignment file: assignment.yaml
# More information on the website https://github.com/m-kru/fp2p.

set_property PACKAGE_PIN A11 [get_ports {out1}]

set_property PACKAGE_PIN A21 [get_ports {out2}]

